/**
 * Auto-Develop Analyzer — Autonomous code fixes via Developer Guardian.
 *
 * Reads CRITICAL/HIGH findings from state, invokes Developer Guardian
 * via CopilotPort with the finding context, and creates draft PRs
 * with the fixes.
 *
 * Design decisions:
 * - Never throws — returns `{ success: false, error }` on failure [CLEAN-CODE]
 * - Only processes CRITICAL and HIGH severity findings [AC2]
 * - Creates draft PRs on `craig/fix-{findingId}` branches [AC3]
 * - Disabled by default (`auto_develop: false`) — opt-in [AC4]
 * - Each finding is processed independently — one failure doesn't block others [CLEAN-CODE]
 * - All dependencies injected via factory params [SOLID/DIP] [HEXAGONAL]
 *
 * @module analyzers/auto-develop
 */

import type { AnalyzerPort } from "../analyzer.port.js";
import type {
  AnalyzerContext,
  AnalyzerResult,
  ActionTaken,
} from "../analyzer.types.js";
import type { CopilotPort } from "../../copilot/index.js";
import type { GitPort } from "../../git-port/index.js";
import type { StatePort, Finding } from "../../state/index.js";
import type { ConfigPort } from "../../config/index.js";
import type { GitOpsPort } from "../auto-fix/auto-fix.ports.js";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Severity levels eligible for autonomous fix. */
const QUALIFYING_SEVERITIES: ReadonlySet<string> = new Set([
  "critical",
  "high",
]);

/** Short timestamp for log lines. */
function ts(): string {
  return new Date().toISOString().slice(11, 19);
}

/** Emoji mapping for severity levels in PR titles. */
const SEVERITY_EMOJI: Readonly<Record<string, string>> = {
  critical: "🔴",
  high: "🟠",
};

// ---------------------------------------------------------------------------
// Factory Dependencies
// ---------------------------------------------------------------------------

/**
 * Dependencies required by the Auto-Develop Analyzer.
 *
 * [SOLID/DIP] All dependencies are ports (interfaces), not implementations.
 */
export interface AutoDevelopDeps {
  readonly copilot: CopilotPort;
  readonly git: GitPort;
  readonly state: StatePort;
  readonly config: ConfigPort;
  readonly gitOps: GitOpsPort;
}

// ---------------------------------------------------------------------------
// Prompt Builder — Pure Function [CLEAN-CODE] [SRP]
// ---------------------------------------------------------------------------

/**
 * Build the prompt sent to Developer Guardian for a finding.
 *
 * Includes all available context: severity, category, file, issue,
 * source, and suggested fix. The Guardian uses this to understand
 * what to fix and where.
 *
 * [CLEAN-CODE] Pure function — no side effects.
 */
function buildFixPrompt(finding: Finding): string {
  const parts: string[] = [
    `Fix the following ${finding.severity.toUpperCase()} finding:`,
    "",
    `**Issue:** ${finding.issue}`,
    `**Severity:** ${finding.severity}`,
    `**Category:** ${finding.category}`,
  ];

  if (finding.file) {
    parts.push(`**File:** ${finding.file}`);
  }

  parts.push(`**Source:** ${finding.source}`);

  parts.push(
    "",
    "Apply the fix following TDD: write a test for the vulnerability first, then fix it.",
    "Ensure the fix does not introduce regressions.",
  );

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// PR Body Builder — Pure Function [CLEAN-CODE] [SRP]
// ---------------------------------------------------------------------------

/**
 * Build the draft PR body for a finding fix.
 *
 * Includes Craig context, finding details, and Developer Guardian output.
 *
 * [CLEAN-CODE] Structured markdown for readability.
 */
function buildPRBody(finding: Finding, guardianOutput: string): string {
  const emoji = SEVERITY_EMOJI[finding.severity] ?? "⚠️";

  return [
    `## 🤖 Craig Auto-Develop`,
    "",
    `This draft PR was automatically created by **Craig** to fix a ${emoji} **${finding.severity.toUpperCase()}** finding.`,
    "",
    `> Craig detected a ${finding.severity} finding and invoked Developer Guardian to create a fix.`,
    `> Please review the changes before merging.`,
    "",
    `### Finding Details`,
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Severity** | ${emoji} ${finding.severity.toUpperCase()} |`,
    `| **Category** | ${finding.category} |`,
    `| **File** | \`${finding.file ?? "N/A"}\` |`,
    `| **Issue** | ${finding.issue} |`,
    `| **Source** | ${finding.source} |`,
    "",
    `### Developer Guardian Output`,
    "",
    guardianOutput,
    "",
    `---`,
    `*This PR was generated by Craig's auto-develop analyzer.*`,
    `*All changes should be reviewed by a human before merging.*`,
  ].join("\n");
}

/**
 * Build the PR title for a finding fix.
 *
 * Format: `fix: {emoji} {truncated issue description}`
 *
 * [CLEAN-CODE] Truncates long issue descriptions to keep titles readable.
 */
function buildPRTitle(finding: Finding): string {
  const emoji = SEVERITY_EMOJI[finding.severity] ?? "⚠️";
  const maxIssueLength = 60;
  const issueText =
    finding.issue.length > maxIssueLength
      ? `${finding.issue.substring(0, maxIssueLength)}...`
      : finding.issue;

  return `fix: ${emoji} ${issueText}`;
}

/**
 * Generate a branch name for a finding fix.
 *
 * Format: `craig/fix-{sanitized-finding-id}`
 * The finding ID is sanitized to be git-branch-safe.
 *
 * [CLEAN-CODE] Deterministic — same finding always produces same branch name.
 */
function buildBranchName(finding: Finding): string {
  const sanitizedId = finding.id
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .substring(0, 40);
  return `craig/fix-${sanitizedId}`;
}

// ---------------------------------------------------------------------------
// Factory Function
// ---------------------------------------------------------------------------

/**
 * Create an Auto-Develop Analyzer instance.
 *
 * Factory function pattern — returns the AnalyzerPort interface.
 * All dependencies are injected; the implementation is encapsulated.
 *
 * @param deps - All required port dependencies
 * @returns An AnalyzerPort instance for autonomous code fixes
 *
 * @example
 * ```typescript
 * const analyzer = createAutoDevelopAnalyzer({
 *   copilot, git, state, config, gitOps,
 * });
 * const result = await analyzer.execute(context);
 * ```
 *
 * [HEXAGONAL] Returns the port interface, not the implementation.
 * [SOLID/DIP] Depends on abstractions (ports), not concretions.
 */
export function createAutoDevelopAnalyzer(
  deps: AutoDevelopDeps,
): AnalyzerPort {
  const { copilot, git, state, config, gitOps } = deps;

  return {
    name: "auto_develop",

    async execute(context: AnalyzerContext): Promise<AnalyzerResult> {
      const startTime = Date.now();

      try {
        return await runAutoDevelop(context, startTime);
      } catch (error: unknown) {
        return {
          success: false,
          summary: error instanceof Error ? error.message : String(error),
          findings: [],
          actions: [],
          duration_ms: Date.now() - startTime,
        };
      }
    },
  };

  // -----------------------------------------------------------------------
  // Core workflow
  // -----------------------------------------------------------------------

  /**
   * Core auto-develop logic — separated from error handling.
   *
   * Steps:
   * 1. Check config (auto_develop enabled? draft PRs enabled?)
   * 2. Query state for CRITICAL/HIGH findings
   * 3. For each qualifying finding:
   *    a. Create fix branch
   *    b. Invoke Developer Guardian
   *    c. If changes exist → commit, push, create draft PR
   *    d. If no changes or failure → cleanup branch
   * 4. Return structured result
   *
   * [CLEAN-CODE] Each step is a small, named function.
   */
  async function runAutoDevelop(
    _context: AnalyzerContext,
    startTime: number,
  ): Promise<AnalyzerResult> {
    // Step 1: Check config
    const cfg = config.get();

    if (!cfg.capabilities.auto_develop) {
      console.error(`[Craig] [${ts()}] auto_develop: disabled by config`);
      return skipResult("auto-develop disabled by config", startTime);
    }

    if (!cfg.autonomy.create_draft_prs) {
      console.error(`[Craig] [${ts()}] auto_develop: draft PRs disabled by config`);
      return skipResult("draft PRs disabled by config", startTime);
    }

    // Step 2: Query qualifying findings
    const allFindings = state.getFindings();
    let qualifyingFindings = allFindings.filter((f) =>
      QUALIFYING_SEVERITIES.has(f.severity),
    );

    // If specific finding IDs were provided, filter to only those
    if (_context.findingIds && _context.findingIds.length > 0) {
      const idSet = new Set(_context.findingIds);
      qualifyingFindings = qualifyingFindings.filter((f) => idSet.has(f.id));
      console.error(`[Craig] [${ts()}] auto_develop: scoped to ${qualifyingFindings.length} findings (${_context.findingIds.length} IDs provided)`);
    }

    if (qualifyingFindings.length === 0) {
      console.error(`[Craig] [${ts()}] auto_develop: no qualifying findings`);
      return skipResult("no qualifying findings (CRITICAL/HIGH)", startTime);
    }

    console.error(`[Craig] [${ts()}] auto_develop: processing ${qualifyingFindings.length} qualifying findings`);

    // Step 3: Process each finding independently
    const actionsTaken: ActionTaken[] = [];
    let fixesApplied = 0;

    for (let i = 0; i < qualifyingFindings.length; i++) {
      const finding = qualifyingFindings[i]!;
      console.error(`[Craig] [${ts()}] auto_develop: [${i + 1}/${qualifyingFindings.length}] ${finding.severity.toUpperCase()}: ${finding.issue.slice(0, 80)}`);
      const action = await processFinding(finding, cfg.branch);
      if (action) {
        actionsTaken.push(action);
        fixesApplied++;
        console.error(`[Craig] [${ts()}] auto_develop: [${i + 1}/${qualifyingFindings.length}] ✅ PR created`);
      } else {
        console.error(`[Craig] [${ts()}] auto_develop: [${i + 1}/${qualifyingFindings.length}] ⏭️ skipped (no changes or failure)`);
      }
    }

    // Step 4: Save state
    await state.save();
    console.error(`[Craig] [${ts()}] auto_develop complete: ${fixesApplied}/${qualifyingFindings.length} fixes applied`);

    return {
      success: true,
      summary: `Auto-develop complete. ${fixesApplied} fix(es) applied out of ${qualifyingFindings.length} qualifying finding(s).`,
      findings: [],
      actions: actionsTaken,
      duration_ms: Date.now() - startTime,
    };
  }

  // -----------------------------------------------------------------------
  // Per-finding processing
  // -----------------------------------------------------------------------

  /**
   * Process a single finding: invoke Guardian → create PR.
   *
   * Returns an ActionTaken if a PR was created, null otherwise.
   * Never throws — catches all errors and logs them.
   *
   * [CLEAN-CODE] Each finding is independent — one failure doesn't block others.
   * [SRP] This function handles the full lifecycle of one finding fix.
   */
  async function processFinding(
    finding: Finding,
    baseBranch: string,
  ): Promise<ActionTaken | null> {
    const branchName = buildBranchName(finding);

    try {
      // Create fix branch
      console.error(`[Craig] [${ts()}]   Creating branch: ${branchName}`);
      await gitOps.createBranch(branchName);

      // Invoke Developer Guardian
      console.error(`[Craig] [${ts()}]   Invoking Developer Guardian...`);
      const invokeResult = await copilot.invoke({
        agent: "dev-guardian",
        prompt: buildFixPrompt(finding),
      });

      // Handle Guardian failure
      if (!invokeResult.success) {
        console.error(`[Craig] [${ts()}]   Developer Guardian failed: ${invokeResult.error}`);
        await safeCleanup(branchName, baseBranch);
        return null;
      }
      console.error(`[Craig] [${ts()}]   Developer Guardian finished: ${invokeResult.duration_ms}ms`);

      // Check if Guardian made any changes
      const hasChanges = await gitOps.hasChanges();
      if (!hasChanges) {
        console.error(`[Craig] [${ts()}]   No file changes detected, skipping`);
        await safeCleanup(branchName, baseBranch);
        return null;
      }

      // Commit, push, create PR
      console.error(`[Craig] [${ts()}]   Committing and pushing to ${branchName}...`);
      const commitMessage = `fix: address ${finding.severity} finding — ${finding.issue}`;
      await gitOps.commitAll(commitMessage);
      await gitOps.push(branchName);

      console.error(`[Craig] [${ts()}]   Creating draft PR...`);
      const pr = await git.createDraftPR({
        title: buildPRTitle(finding),
        body: buildPRBody(finding, invokeResult.output),
        head: branchName,
        base: baseBranch,
        draft: true,
      });

      return {
        type: "pr_opened",
        url: pr.url,
        description: `Draft PR #${pr.number}: fix ${finding.severity} finding — ${finding.issue}`,
      };
    } catch (error: unknown) {
      console.error(
        `[Craig] Failed to process finding ${finding.id}: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
      await safeCleanup(branchName, baseBranch);
      return null;
    }
  }

  // -----------------------------------------------------------------------
  // Helpers
  // -----------------------------------------------------------------------

  /**
   * Build a skip result — used when config disables the analyzer
   * or no qualifying findings are found.
   */
  function skipResult(reason: string, startTime: number): AnalyzerResult {
    return {
      success: true,
      summary: reason,
      findings: [],
      actions: [],
      duration_ms: Date.now() - startTime,
    };
  }

  /**
   * Cleanup branch without throwing — used in catch blocks.
   *
   * [CLEAN-CODE] Don't mask the original error with cleanup errors.
   */
  async function safeCleanup(
    branchName: string,
    defaultBranch: string,
  ): Promise<void> {
    try {
      await gitOps.cleanup(branchName, defaultBranch);
    } catch {
      // Swallow cleanup errors — the original error is more important
    }
  }
}
